<?php session_start();
include("../../login/sesion_start.php");
include("../../librerias/librerias.php");
include("../../cabecera.php");
$conn=db_connect();
$usr_nombre=mysql_real_escape_string($_POST['usr_nombre']);
$usr_apellidos=mysql_real_escape_string($_POST['usr_apellidos']);
$usr_login=mysql_real_escape_string($_POST['usr_login']);
$usr_email=mysql_real_escape_string($_POST['usr_email']);
$usr_dni=mysql_real_escape_string($_POST['usr_dni']);
$usr_perfil=mysql_real_escape_string($_POST['usr_perfil']);
$usr_categoria=mysql_real_escape_string($_POST['usr_categoria']);
$usr_dep_id=$_POST['usr_dep_id'];
$usr_cen_id=$_POST['usr_cen_id'];
$usr_superior_id=$_POST['usr_superior_id'];
$usr_password = md5($_POST['usr_password']);
$query="INSERT INTO usuarios (usr_nombre, usr_apellidos, usr_cen_id, usr_dep_id, usr_dni, usr_email, usr_password, usr_perfil, usr_superior_id, usr_categoria, usr_login) VALUES ('".utf8_decode($usr_nombre)."', '".utf8_decode($usr_apellidos)."', '".$usr_cen_id."', '".$usr_dep_id."', '".utf8_decode($usr_dni)."', '".utf8_decode($usr_email)."', '".$usr_password."', '".$usr_perfil."', '".$usr_superior_id."', '".utf8_decode($usr_categoria)."', '".utf8_decode($usr_login)."')";
$result=mysql_query($query) or die("No se puede ejecutar la sentencia: ".$query);
header('Location: index.php');
?>
