version: "3.2"

services:
  apache_old_airpharm:
    build:
      context: './docker/apache/'

    # links:
    #   - mysql_old_airpharm:mysql_old_airpharm

    # depends_on:
    #   - mysql_old_airpharm

    ports:
      - "0:80"
    volumes:
      - ./:/var/www/html/
      - ./docker/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache/php.ini:/usr/local/etc/php/php.ini

    container_name:
      apache_old_airpharm

  # mysql_old_airpharm:
  #   build:
  #     context    : ./
  #     dockerfile : ./docker/mysql/Dockerfile
  #
  #   command: [
  #     '--character-set-server=utf8mb4',
  #     '--collation-server=utf8mb4_unicode_ci',
  #     '--default-authentication-plugin=mysql_native_password',
  #   ]
  #
  #   restart:
  #     always
  #
  #   volumes:
  #     - ./docker/initdb:/docker-entrypoint-initdb.d
  #     - ./docker/mysql/logs:/var/log/mysql
  #
  #   ports:
  #     - "0:3306"
  #
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #
  #   container_name:
  #     mysql_old_airpharm
