<?php session_start();
include("../login/sesion_start.php");
include("../librerias/librerias.php");
include("../cabecera.php");
$ano=$_SESSION['ano'];
$conn=db_connect();
$ale_med1_recordatorio=mysql_real_escape_string($_POST['ale_med1_recordatorio']);
$ale_med1_fechalimite=mysql_real_escape_string($_POST['ale_med1_fechalimite']);
$ale_med1_temp=mysql_real_escape_string($_POST['ale_med1_temp']);
$ale_med1_texto=mysql_real_escape_string($_POST['ale_med1_texto']);
$ale_med2_recordatorio=mysql_real_escape_string($_POST['ale_med2_recordatorio']);
$ale_med2_fechalimite=mysql_real_escape_string($_POST['ale_med2_fechalimite']);
$ale_med2_temp=mysql_real_escape_string($_POST['ale_med2_temp']);
$ale_med2_texto=mysql_real_escape_string($_POST['ale_med2_texto']);
$ale_med3_recordatorio=mysql_real_escape_string($_POST['ale_med3_recordatorio']);
$ale_med3_fechalimite=mysql_real_escape_string($_POST['ale_med3_fechalimite']);
$ale_med3_temp=mysql_real_escape_string($_POST['ale_med3_temp']);
$ale_med3_texto=mysql_real_escape_string($_POST['ale_med3_texto']);
$ale_med4_recordatorio=mysql_real_escape_string($_POST['ale_med4_recordatorio']);
$ale_med4_fechalimite=mysql_real_escape_string($_POST['ale_med4_fechalimite']);
$ale_med4_temp=mysql_real_escape_string($_POST['ale_med4_temp']);
$ale_med4_texto=mysql_real_escape_string($_POST['ale_med4_texto']);
$ale_medf_recordatorio=mysql_real_escape_string($_POST['ale_medf_recordatorio']);
$ale_medf_fechalimite=mysql_real_escape_string($_POST['ale_medf_fechalimite']);
$ale_medf_temp=mysql_real_escape_string($_POST['ale_medf_temp']);
$ale_medf_texto=mysql_real_escape_string($_POST['ale_medf_texto']);
$ale_defp_recordatorio=mysql_real_escape_string($_POST['ale_defp_recordatorio']);
$ale_defp_fechalimite=mysql_real_escape_string($_POST['ale_defp_fechalimite']);
$ale_defp_temp=mysql_real_escape_string($_POST['ale_defp_temp']);
$ale_defp_texto=mysql_real_escape_string($_POST['ale_defp_texto']);
$ale_deff_recordatorio=mysql_real_escape_string($_POST['ale_deff_recordatorio']);
$ale_deff_fechalimite=mysql_real_escape_string($_POST['ale_deff_fechalimite']);
$ale_deff_temp=mysql_real_escape_string($_POST['ale_deff_temp']);
$ale_deff_texto=mysql_real_escape_string($_POST['ale_deff_texto']);
$query="UPDATE alertas SET ale_med1_recordatorio='".cambiaf_a_mysql($ale_med1_recordatorio)."', ale_med1_fechalimite='".cambiaf_a_mysql($ale_med1_fechalimite)."', ale_med1_temp='".$ale_med1_temp."', ale_med1_texto='".utf8_decode($ale_med1_texto)."',ale_med2_recordatorio='".cambiaf_a_mysql($ale_med2_recordatorio)."', ale_med2_fechalimite='".cambiaf_a_mysql($ale_med2_fechalimite)."', ale_med2_temp='".$ale_med2_temp."', ale_med2_texto='".utf8_decode($ale_med2_texto)."',ale_med3_recordatorio='".cambiaf_a_mysql($ale_med3_recordatorio)."', ale_med3_fechalimite='".cambiaf_a_mysql($ale_med3_fechalimite)."', ale_med3_temp='".$ale_med3_temp."', ale_med3_texto='".utf8_decode($ale_med3_texto)."',ale_med4_recordatorio='".cambiaf_a_mysql($ale_med4_recordatorio)."', ale_med4_fechalimite='".cambiaf_a_mysql($ale_med4_fechalimite)."', ale_med4_temp='".$ale_med4_temp."', ale_med4_texto='".utf8_decode($ale_med4_texto)."',ale_medf_recordatorio='".cambiaf_a_mysql($ale_medf_recordatorio)."', ale_medf_fechalimite='".cambiaf_a_mysql($ale_medf_fechalimite)."', ale_medf_temp='".$ale_medf_temp."', ale_medf_texto='".utf8_decode($ale_medf_texto)."' WHERE ale_ano=".$ano;
$result=mysql_query($query) or die("No se puede ejecutar la sentencia: ".$query);
$query="UPDATE alertas SET ale_defp_recordatorio='".cambiaf_a_mysql($ale_defp_recordatorio)."', ale_defp_fechalimite='".cambiaf_a_mysql($ale_defp_fechalimite)."', ale_defp_temp='".$ale_defp_temp."', ale_defp_texto='".utf8_decode($ale_defp_texto)."',ale_deff_recordatorio='".cambiaf_a_mysql($ale_deff_recordatorio)."', ale_deff_fechalimite='".cambiaf_a_mysql($ale_deff_fechalimite)."', ale_deff_temp='".$ale_deff_temp."', ale_deff_texto='".utf8_decode($ale_deff_texto)."' WHERE ale_ano=".$ano;
$result=mysql_query($query) or die("No se puede ejecutar la sentencia: ".$query);
header('Location: index.php');
?>
