	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<?php 
include("../login/sesion_start.php");
include("../librerias/librerias.php");
require('../fpdf/fpdf.php');
$conn=db_connect();
$dpo_id=$_GET['dpo_id'];
$valor_sim=$_GET['valor_sim'];
$query="SELECT * FROM vdpo_cabeceras WHERE dpo_id=".$dpo_id;
$result=mysql_query($query) or die ("No se puede ejecutar la sentencia: ".$query);
$row=mysql_fetch_array($result);
$query_lin="SELECT * FROM vdpo_lineas WHERE dl_dpo_id=".$row['dpo_id'];
$result_lin=mysql_query($query_lin) or die ("No se puede ejecutar la sentencia: ".$query_lin);
$total_q1=0;
$total_q2=0;
$total_q3=0;
$total_q4=0;
$total_anual=0;
while($row_lin=mysql_fetch_array($result_lin)){
	$peso[$row_lin['obj_tipo']]+=$row_lin['dl_peso'];
	$peso['total']+=$row_lin['dl_peso'];
	$total_q1+=por_obtencion($row_lin['dl_id'],1);
	$total_q2+=por_obtencion($row_lin['dl_id'],2);
	$total_q3+=por_obtencion($row_lin['dl_id'],3);
	$total_q4+=por_obtencion($row_lin['dl_id'],4);
	$total_anual+=por_obtencion($row_lin['dl_id'],'Anual');
}
$nombre=utf8_encode($row['usr_nombre']).' '.utf8_encode($row['usr_apellidos']).' ('.$row['dpo_ano'].')';
$fecha=date('d/m/Y');

class PDF extends FPDF
{
function Header()
{
		global $valor_sim;
		global $nombre;
    	$this->SetFont('Arial','B',10);
		$this->SetTextColor(0);
    	//Título
    	$this->Cell(100,4,'DPO de '.$nombre,'B');
    	$this->Cell(0,4,'Importe de simulación: '.number_format($valor_sim,0,',','.').' €','B',0,'R');
		$this->Ln();
    	$this->SetFont('Arial','B',10);
}
function Footer()
{
	global $fecha;
	$this->SetTextColor(0,0,0);
   	$this->SetY(-15);
	$this->SetFont('Arial','B',8);
	$this->Cell(120,4,'Fecha informe: '.$fecha,'T',0,'L');
    $this->Cell(0,4,'Página: '.$this->PageNo().'/{nb}','T',0,'R');
}

}
ob_end_clean();
$pdf=new PDF();
$pdf->AliasNbPages();
$pdf->AddPage('L');
$n_lin=1;
$query_lin="SELECT * FROM vdpo_lineas WHERE dl_dpo_id=".$dpo_id." AND obj_tipo LIKE 'Objetivo de compañia' ORDER BY dl_peso DESC, obj_descripcion ASC";
$result_lin=mysql_query($query_lin) or die ("No se puede ejecutar la sentencia: ".$query_lin);
$num_lin=mysql_num_rows($result_lin);
if($num_lin){
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(197,4,'A nivel de compañia',0,0,'L',true);
	$pdf->Cell(10,4,$peso['Objetivo de Compañía'].' %',0,0,'R',true);
	$pdf->Cell(0,4,'',0,1,'R',true);
	$pdf->SetFillColor(120);
	$pdf->Cell(4,4,'',0,0,'C',true);
	$pdf->Cell(70,4,'Objetivo',0,0,'L',true);
	$pdf->Cell(12,4,'C.I.',0,0,'C',true);
	$pdf->Cell(70,4,'Indicador',0,0,'L',true);
	$pdf->Cell(13,4,'Meta',0,0,'C',true);
	$pdf->Cell(8,4,'Un',0,0,'C',true);
	$pdf->Cell(20,4,'Horquilla',0,0,'C',true);
	$pdf->Cell(10,4,'Peso',0,0,'C',true);
	$pdf->Cell(10,4,'T1',0,0,'C',true);
	$pdf->Cell(10,4,'T2',0,0,'C',true);
	$pdf->Cell(10,4,'T3',0,0,'C',true);
	$pdf->Cell(10,4,'T4',0,0,'C',true);
	$pdf->Cell(10,4,'Final',0,0,'C',true);
	$pdf->Cell(20,4,'Simulacion',0,1,'C',true);
	
	$yfinal=$pdf->y;
}
	while($row_lin=mysql_fetch_array($result_lin)){
		if($pdf->y>170){
			$pdf->AddPage('L');			
			$yfinal=14;
		}
		$pdf->y=$yfinal;
		$yorigen=$pdf->y;
		$pdf->SetFont('Arial','',6);
		$pdf->SetTextColor(0);
		$pdf->Cell(4,4,$n_lin,0,0,'R');
		$n_lin++;
		$pdf->SetFont('Arial','',7);
		$yfinal=$pdf->y;
		if(strpos($row_lin['obj_descripcion'],'<strong>')==0){
			$obj_descripcion=str_replace('<strong>','',$row_lin['obj_descripcion']);
			$obj_descripcion=str_replace('</strong>','',$obj_descripcion);
			$pdf->MultiCell(70,4,$obj_descripcion);
		}else{
			$pdf->MultiCell(70,4,$row_lin['obj_descripcion']);
		}
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->MultiCell(12,4,$row_lin['ind_codigo']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->MultiCell(70,4,$row_lin['ind_nombre']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->MultiCell(13,4,number_format($row_lin['oa_meta'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->MultiCell(8,4,$row_lin['ind_meta_un_abreviatura']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_min'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_max'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=207;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_peso'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=217;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q1'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q2'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q3'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q4'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=257;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_anual'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=267;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format(sim_anual($row_lin['dl_id']),2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=277;
		$pdf->y=$yorigen;
		$pdf->MultiCell(0,4,number_format((por_obtencion($row_lin['dl_id'])*$valor_sim)/100,2,',','.').'€');
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$total_por_sim+=por_obtencion($row_lin['dl_id']);
		$total_sim+=por_obtencion($row_lin['dl_id'])*$valor_sim/100;
		$altura=$yfinal-$yorigen;
		$pdf->y=$yorigen;
		$pdf->Cell(4,$altura,'',1);
		$pdf->x=14;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->Cell(12,$altura,'',1);
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(180,253,180);
		$pdf->Cell(13,$altura,number_format($row_lin['oa_meta'],2,',','.'),1,0,'R',true);
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->Cell(8,$altura,$row_lin['ind_meta_un_abreviatura'],1,0,'R',true);
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(231,229,227);
		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_min'],2,',','.'),1,0,'R',true);
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_max'],2,',','.'),1,0,'R',true);
		$pdf->x=207;
		$pdf->SetFillColor(184,184,112);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['dl_peso'],2,',','.'),1,0,'R',true);
		$pdf->x=217;
		$pdf->SetFillColor(231,229,227);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q1']),1,0,'R',true);
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q2']),1,0,'R',true);
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q3']),1,0,'R',true);
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q4']),1,0,'R',true);
		$pdf->x=257;
		$pdf->SetFillColor(180,253,180);
		if(((floatval ($row_lin['oa_horquilla_min'])<=floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])<floatval ($row_lin['oa_horquilla_max']))) or ((floatval ($row_lin['oa_horquilla_min'])>floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])>floatval ($row_lin['oa_horquilla_max'])))){
			$pdf->SetTextColor(255,0,0);
		}
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_anual']),1,1,'R',true);
		$pdf->SetTextColor(0);
		$pdf->x=267;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(231,229,227);
		$pdf->Cell(10,$altura,imprimir_valor(sim_anual($row_lin['dl_id'])),1,1,'R',true);
		$pdf->x=277;
		$pdf->SetFillColor(180,253,180);
		$pdf->y=$yorigen;
		$pdf->Cell(0,$altura,number_format(((por_obtencion($row_lin['dl_id'])*$valor_sim)/100),0,',','.'),1,1,'R',true);
		$pdf->SetFillColor(231,229,227);
 }
$query_lin="SELECT * FROM vdpo_lineas WHERE dl_dpo_id=".$row['dpo_id']." AND (obj_tipo LIKE 'Para el Comité de Dirección' OR obj_tipo LIKE '".utf8_decode('Mandos Intermedios')."') ORDER BY dl_peso DESC, obj_descripcion ASC";
		$result_lin=mysql_query($query_lin) or die ("No se puede ejecutar la sentencia: ".$query_lin);
		$num_lin=mysql_num_rows($result_lin);
		if($num_lin){
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
		if($row['usr_categoria']=='Dirección'){
          $tipo="A nivel de comité de dirección";
           }else{
          $tipo="A nivel de Mandos Intermedios";
          }
	$pdf->Cell(197,4,$tipo,0,0,'L',true);
	$pdf->Cell(10,4,$peso['Para el Comité de Dirección']+$peso['Mandos Intermedios'].' %',0,0,'R',true);
	$pdf->Cell(0,4,'',0,1,'R',true);
	$pdf->SetFillColor(120);
	$pdf->Cell(4,4,'',0,0,'C',true);
	$pdf->Cell(70,4,'Objetivo',0,0,'L',true);
	$pdf->Cell(12,4,'C.I.',0,0,'C',true);
	$pdf->Cell(70,4,'Indicador',0,0,'L',true);
	$pdf->Cell(13,4,'Meta',0,0,'C',true);
	$pdf->Cell(8,4,'Un',0,0,'C',true);
	$pdf->Cell(20,4,'Horquilla',0,0,'C',true);
	$pdf->Cell(10,4,'Peso',0,0,'C',true);
	$pdf->Cell(10,4,'T1',0,0,'C',true);
	$pdf->Cell(10,4,'T2',0,0,'C',true);
	$pdf->Cell(10,4,'T3',0,0,'C',true);
	$pdf->Cell(10,4,'T4',0,0,'C',true);
	$pdf->Cell(10,4,'Final',0,0,'C',true);
	$pdf->Cell(20,4,'Simulacion',0,1,'C',true);
	
	$yfinal=$pdf->y;
}
	while($row_lin=mysql_fetch_array($result_lin)){
		if($pdf->y>170){
			$pdf->AddPage('L');			
			$yfinal=14;
		}
		$pdf->y=$yfinal;
		$yorigen=$pdf->y;
		$pdf->SetFont('Arial','',6);
		$pdf->SetTextColor(0);
		$pdf->Cell(4,4,$n_lin,0,0,'R');
		$n_lin++;
		$pdf->SetFont('Arial','',7);
		$yfinal=$pdf->y;
		if(strpos($row_lin['obj_descripcion'],'<strong>')==0){
			$obj_descripcion=str_replace('<strong>','',$row_lin['obj_descripcion']);
			$obj_descripcion=str_replace('</strong>','',$obj_descripcion);
			$pdf->MultiCell(70,4,$obj_descripcion);
		}else{
			$pdf->MultiCell(70,4,$row_lin['obj_descripcion']);
		}
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->MultiCell(12,4,$row_lin['ind_codigo']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->MultiCell(70,4,$row_lin['ind_nombre']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->MultiCell(13,4,number_format($row_lin['oa_meta'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->MultiCell(8,4,$row_lin['ind_meta_un_abreviatura']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_min'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_max'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=207;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_peso'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=217;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q1'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q2'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q3'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q4'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=257;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_anual'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=267;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format(sim_anual($row_lin['dl_id']),2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=277;
		$pdf->y=$yorigen;
		$pdf->MultiCell(0,4,number_format((por_obtencion($row_lin['dl_id'])*$valor_sim)/100,2,',','.').'€');
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$total_por_sim+=por_obtencion($row_lin['dl_id']);
		$total_sim+=por_obtencion($row_lin['dl_id'])*$valor_sim/100;
		$altura=$yfinal-$yorigen;
		$pdf->y=$yorigen;
		$pdf->Cell(4,$altura,'',1);
		$pdf->x=14;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->Cell(12,$altura,'',1);
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(180,253,180);
		$pdf->Cell(13,$altura,number_format($row_lin['oa_meta'],2,',','.'),1,0,'R',true);
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->Cell(8,$altura,$row_lin['ind_meta_un_abreviatura'],1,0,'R',true);
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(231,229,227);

		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_min'],2,',','.'),1,0,'R',true);
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_max'],2,',','.'),1,0,'R',true);
		$pdf->x=207;
		$pdf->SetFillColor(184,184,112);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['dl_peso'],2,',','.'),1,0,'R',true);
		$pdf->x=217;
		$pdf->SetFillColor(231,229,227);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q1']),1,0,'R',true);
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q2']),1,0,'R',true);
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q3']),1,0,'R',true);
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q4']),1,0,'R',true);
		$pdf->x=257;
		$pdf->SetFillColor(180,253,180);
		$pdf->y=$yorigen;
		if(((floatval ($row_lin['oa_horquilla_min'])<=floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])<floatval ($row_lin['oa_horquilla_max']))) or ((floatval ($row_lin['oa_horquilla_min'])>floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])>floatval ($row_lin['oa_horquilla_max'])))){
			$pdf->SetTextColor(255,0,0);
		}
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_anual']),1,1,'R',true);
		$pdf->SetTextColor(0);
		$pdf->x=267;
		$pdf->SetFillColor(231,229,227);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor(sim_anual($row_lin['dl_id'])),1,1,'R',true);
		$pdf->x=277;
		$pdf->SetFillColor(180,253,180);
		$pdf->y=$yorigen;
		$pdf->Cell(0,$altura,number_format(((por_obtencion($row_lin['dl_id'])*$valor_sim)/100),0,',','.'),1,1,'R',true);
		$pdf->SetFillColor(231,229,227);
 }
		$query_lin="SELECT * FROM vdpo_lineas WHERE dl_dpo_id=".$row['dpo_id']." AND (obj_tipo LIKE '".utf8_decode('de departamento')."' OR obj_tipo LIKE '".utf8_decode('Proyectos')."') ORDER BY dl_peso DESC, obj_descripcion ASC";
		$result_lin=mysql_query($query_lin) or die ("No se puede ejecutar la sentencia: ".$query_lin);
		$num_lin=mysql_num_rows($result_lin);
if($num_lin){
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(197,4,'A nivel Departamental',0,0,'L',true);
	$pdf->Cell(10,4,$peso['de departamento']+$peso['Proyectos'].' %',0,0,'R',true);
	$pdf->Cell(0,4,'',0,1,'R',true);
	$pdf->SetFillColor(120);
	$pdf->Cell(4,4,'',0,0,'C',true);
	$pdf->Cell(70,4,'Objetivo',0,0,'L',true);
	$pdf->Cell(12,4,'C.I.',0,0,'C',true);
	$pdf->Cell(70,4,'Indicador',0,0,'L',true);
	$pdf->Cell(13,4,'Meta',0,0,'C',true);
	$pdf->Cell(8,4,'Un',0,0,'C',true);
	$pdf->Cell(20,4,'Horquilla',0,0,'C',true);
	$pdf->Cell(10,4,'Peso',0,0,'C',true);
	$pdf->Cell(10,4,'T1',0,0,'C',true);
	$pdf->Cell(10,4,'T2',0,0,'C',true);
	$pdf->Cell(10,4,'T3',0,0,'C',true);
	$pdf->Cell(10,4,'T4',0,0,'C',true);
	$pdf->Cell(10,4,'Final',0,0,'C',true);
	$pdf->Cell(20,4,'Simulacion',0,1,'C',true);
	
	$yfinal=$pdf->y;
}
	while($row_lin=mysql_fetch_array($result_lin)){
		if($pdf->y>170){
			$pdf->AddPage('L');			
			$yfinal=14;
		}
		$pdf->y=$yfinal;
		$yorigen=$pdf->y;
		$pdf->SetFont('Arial','',6);
		$pdf->SetTextColor(0);
		$pdf->Cell(4,4,$n_lin,0,0,'R');
		$n_lin++;
		$pdf->SetFont('Arial','',7);
		$yfinal=$pdf->y;
		if(strpos($row_lin['obj_descripcion'],'<strong>')==0){
			$obj_descripcion=str_replace('<strong>','',$row_lin['obj_descripcion']);
			$obj_descripcion=str_replace('</strong>','',$obj_descripcion);
			$pdf->MultiCell(70,4,$obj_descripcion);
		}else{
			$pdf->MultiCell(70,4,$row_lin['obj_descripcion']);
		}
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->MultiCell(12,4,$row_lin['ind_codigo']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->MultiCell(70,4,$row_lin['ind_nombre']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->MultiCell(13,4,number_format($row_lin['oa_meta'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->MultiCell(8,4,$row_lin['ind_meta_un_abreviatura']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_min'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_max'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=207;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_peso'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=217;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q1'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q2'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q3'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q4'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=257;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_anual'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=267;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format(sim_anual($row_lin['dl_id']),2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=277;
		$pdf->y=$yorigen;
		$pdf->MultiCell(0,4,number_format((por_obtencion($row_lin['dl_id'])*$valor_sim)/100,2,',','.').'€');
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$total_por_sim+=por_obtencion($row_lin['dl_id']);
		$total_sim+=por_obtencion($row_lin['dl_id'])*$valor_sim/100;
		$altura=$yfinal-$yorigen;
		$pdf->y=$yorigen;
		$pdf->Cell(4,$altura,'',1);
		$pdf->x=14;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->Cell(12,$altura,'',1);
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(180,253,180);
		$pdf->Cell(13,$altura,number_format($row_lin['oa_meta'],2,',','.'),1,0,'R',true);
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->Cell(8,$altura,$row_lin['ind_meta_un_abreviatura'],1,0,'R',true);
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(231,229,227);

		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_min'],2,',','.'),1,0,'R',true);
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_max'],2,',','.'),1,0,'R',true);
		$pdf->x=207;
		$pdf->SetFillColor(184,184,112);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['dl_peso'],2,',','.'),1,0,'R',true);
		$pdf->x=217;
		$pdf->SetFillColor(231,229,227);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q1']),1,0,'R',true);
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q2']),1,0,'R',true);
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q3']),1,0,'R',true);
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q4']),1,0,'R',true);
		$pdf->x=257;
		$pdf->SetFillColor(180,253,180);
		if(((floatval ($row_lin['oa_horquilla_min'])<=floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])<floatval ($row_lin['oa_horquilla_max']))) or ((floatval ($row_lin['oa_horquilla_min'])>floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])>floatval ($row_lin['oa_horquilla_max'])))){
			$pdf->SetTextColor(255,0,0);
		}
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_anual']),1,1,'R',true);
		$pdf->SetTextColor(0);
		$pdf->x=267;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(231,229,227);
		$pdf->Cell(10,$altura,imprimir_valor(sim_anual($row_lin['dl_id'])),1,1,'R',true);
		$pdf->SetFillColor(180,253,180);
		$pdf->x=277;
		$pdf->y=$yorigen;
		$pdf->Cell(0,$altura,number_format(((por_obtencion($row_lin['dl_id'])*$valor_sim)/100),0,',','.'),1,1,'R',true);
		$pdf->SetFillColor(231,229,227);
 }
$query_lin="SELECT * FROM vdpo_lineas WHERE dl_dpo_id=".$row['dpo_id']." AND obj_tipo LIKE '".utf8_decode('Personal')."' ORDER BY dl_peso DESC, obj_descripcion ASC";
$result_lin=mysql_query($query_lin) or die ("No se puede ejecutar la sentencia: ".$query_lin);
$num_lin=mysql_num_rows($result_lin);
if($num_lin){
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(197,4,'A nivel Personal',0,0,'L',true);
	$pdf->Cell(10,4,$peso['Personal'].' %',0,0,'R',true);
	$pdf->Cell(0,4,'',0,1,'R',true);
	$pdf->SetFillColor(120);
	$pdf->Cell(4,4,'',0,0,'C',true);
	$pdf->Cell(70,4,'Objetivo',0,0,'L',true);
	$pdf->Cell(12,4,'C.I.',0,0,'C',true);
	$pdf->Cell(70,4,'Indicador',0,0,'L',true);
	$pdf->Cell(13,4,'Meta',0,0,'C',true);
	$pdf->Cell(8,4,'Un',0,0,'C',true);
	$pdf->Cell(20,4,'Horquilla',0,0,'C',true);
	$pdf->Cell(10,4,'Peso',0,0,'C',true);
	$pdf->Cell(10,4,'T1',0,0,'C',true);
	$pdf->Cell(10,4,'T2',0,0,'C',true);
	$pdf->Cell(10,4,'T3',0,0,'C',true);
	$pdf->Cell(10,4,'T4',0,0,'C',true);
	$pdf->Cell(10,4,'Final',0,0,'C',true);
	$pdf->Cell(20,4,'Simulacion',0,1,'C',true);
	
	$yfinal=$pdf->y;
}
	while($row_lin=mysql_fetch_array($result_lin)){
		if($pdf->y>170){
			$pdf->AddPage('L');			
			$yfinal=14;
		}
		$pdf->y=$yfinal;
		$yorigen=$pdf->y;
		$pdf->SetFont('Arial','',6);
		$pdf->SetTextColor(0);
		$pdf->Cell(4,4,$n_lin,0,0,'R');
		$n_lin++;
		$pdf->SetFont('Arial','',7);
		$yfinal=$pdf->y;
		if(strpos($row_lin['obj_descripcion'],'<strong>')==0){
			$obj_descripcion=str_replace('<strong>','',$row_lin['obj_descripcion']);
			$obj_descripcion=str_replace('</strong>','',$obj_descripcion);
			$pdf->MultiCell(70,4,$obj_descripcion);
		}else{
			$pdf->MultiCell(70,4,$row_lin['obj_descripcion']);
		}
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->MultiCell(12,4,$row_lin['ind_codigo']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->MultiCell(70,4,$row_lin['ind_nombre']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->MultiCell(13,4,number_format($row_lin['oa_meta'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->MultiCell(8,4,$row_lin['ind_meta_un_abreviatura']);
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_min'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['oa_horquilla_max'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=207;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_peso'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=217;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q1'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q2'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q3'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_q4'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=257;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format($row_lin['dl_rdo_anual'],2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=267;
		$pdf->y=$yorigen;
		$pdf->MultiCell(10,4,number_format(sim_anual($row_lin['dl_id']),2,',','.'));
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$pdf->x=277;
		$pdf->y=$yorigen;
		$pdf->MultiCell(0,4,number_format((por_obtencion($row_lin['dl_id'])*$valor_sim)/100,2,',','.').'€');
		if($pdf->y>$yfinal){
			$yfinal=$pdf->y;
		}
		$total_por_sim+=por_obtencion($row_lin['dl_id']);
		$total_sim+=por_obtencion($row_lin['dl_id'])*$valor_sim/100;
		$altura=$yfinal-$yorigen;
		$pdf->y=$yorigen;
		$pdf->Cell(4,$altura,'',1);
		$pdf->x=14;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=84;
		$pdf->y=$yorigen;
		$pdf->Cell(12,$altura,'',1);
		$pdf->x=96;
		$pdf->y=$yorigen;
		$pdf->Cell(70,$altura,'',1);
		$pdf->x=166;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(180,253,180);
		$pdf->Cell(13,$altura,number_format($row_lin['oa_meta'],2,',','.'),1,0,'R',true);
		$pdf->x=179;
		$pdf->y=$yorigen;
		$pdf->Cell(8,$altura,$row_lin['ind_meta_un_abreviatura'],1,0,'R',true);
		$pdf->x=187;
		$pdf->y=$yorigen;
		$pdf->SetFillColor(231,229,227);

		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_min'],2,',','.'),1,0,'R',true);
		$pdf->x=197;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['oa_horquilla_max'],2,',','.'),1,0,'R',true);
		$pdf->x=207;
		$pdf->SetFillColor(184,184,112);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,number_format($row_lin['dl_peso'],2,',','.'),1,0,'R',true);
		$pdf->x=217;
		$pdf->SetFillColor(231,229,227);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q1']),1,0,'R',true);
		$pdf->x=227;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q2']),1,0,'R',true);
		$pdf->x=237;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q3']),1,0,'R',true);
		$pdf->x=247;
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_q4']),1,0,'R',true);
		$pdf->x=257;
		$pdf->SetFillColor(180,253,180);
		if(((floatval ($row_lin['oa_horquilla_min'])<=floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])<floatval ($row_lin['oa_horquilla_max']))) or ((floatval ($row_lin['oa_horquilla_min'])>floatval ($row_lin['oa_horquilla_max'])) and (floatval ($row_lin['dl_rdo_anual'])>floatval ($row_lin['oa_horquilla_max'])))){
			$pdf->SetTextColor(255,0,0);
		}
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor($row_lin['dl_rdo_anual']),1,1,'R',true);
		$pdf->SetTextColor(0);
		$pdf->x=267;
		$pdf->SetFillColor(231,229,227);
		$pdf->y=$yorigen;
		$pdf->Cell(10,$altura,imprimir_valor(sim_anual($row_lin['dl_id'])),1,1,'R',true);
		$pdf->x=277;
		$pdf->SetFillColor(180,253,180);
		$pdf->y=$yorigen;
		$pdf->Cell(0,$altura,number_format(((por_obtencion($row_lin['dl_id'])*$valor_sim)/100),0,',','.'),1,1,'R',true);
		$pdf->SetFillColor(231,229,227);
 }
	$pdf->SetFont('Arial','B',7);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(197,4,'TOTAL',0,0,'L',true);
	$pdf->Cell(10,4,$peso['total'].' %',0,0,'R',true);
	$pdf->Cell(10,4,number_format($total_q1,2,',','.'),0,0,'R',true);
	$pdf->Cell(10,4,number_format($total_q2,2,',','.'),0,0,'R',true);
	$pdf->Cell(10,4,number_format($total_q3,2,',','.'),0,0,'R',true);
	$pdf->Cell(10,4,number_format($total_q4,2,',','.'),0,0,'R',true);
/*	$pdf->SetFillColor(180,253,180);
	$pdf->SetTextColor(0);
*/	$pdf->Cell(10,4,number_format($total_anual,2,',','.'),0,0,'R',true);
	$pdf->SetFillColor(0);
	$pdf->SetTextColor(255);
	$pdf->Cell(10,4,number_format($total_por_sim,2,',','.'),0,0,'R',true);
/*	$pdf->SetFillColor(180,253,180);
	$pdf->SetTextColor(0);
*/	$pdf->Cell(10,4,number_format($total_sim,0,',','.'),0,1,'R',true);
	$pdf->AddPage('L');
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(0,4,'Enero-Marzo',0,1,'L',true);
	$pdf->SetFillColor(120);
    $query_com="SELECT * FROM dpo_comentarios WHERE com_dpo_id=".$dpo_id." AND com_periodo='Enero-Marzo' ORDER BY com_n_lin ASC";
    $result_com=mysql_query($query_com) or die ("No se puede ejecutar la consulta: ".$query_com);
	while($row_com=mysql_fetch_array($result_com)){
		$pdf->SetFont('Arial','',7);
		$pdf->SetTextColor(0);
		$pdf->MultiCell(0,4,$row_com['com_n_lin'].'. '.$row_com['com_comentario'],1);
	}
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(0,4,'Abril-Junio',0,1,'L',true);
	$pdf->SetFillColor(120);
    $query_com="SELECT * FROM dpo_comentarios WHERE com_dpo_id=".$dpo_id." AND com_periodo='Abril-Junio' ORDER BY com_n_lin ASC";
    $result_com=mysql_query($query_com) or die ("No se puede ejecutar la consulta: ".$query_com);
	while($row_com=mysql_fetch_array($result_com)){
		$pdf->SetFont('Arial','',7);
		$pdf->SetTextColor(0);
		$pdf->MultiCell(0,4,$row_com['com_n_lin'].'. '.$row_com['com_comentario'],1);
	}
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(0,4,'Julio-Septiembre',0,1,'L',true);
	$pdf->SetFillColor(120);
    $query_com="SELECT * FROM dpo_comentarios WHERE com_dpo_id=".$dpo_id." AND com_periodo='Julio-Septiembre' ORDER BY com_n_lin ASC";
    $result_com=mysql_query($query_com) or die ("No se puede ejecutar la consulta: ".$query_com);
	while($row_com=mysql_fetch_array($result_com)){
		$pdf->SetFont('Arial','',7);
		$pdf->SetTextColor(0);
		$pdf->MultiCell(0,4,$row_com['com_n_lin'].'. '.$row_com['com_comentario'],1);
	}
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(0,4,'Octubre-Diciembre',0,1,'L',true);
	$pdf->SetFillColor(120);
    $query_com="SELECT * FROM dpo_comentarios WHERE com_dpo_id=".$dpo_id." AND com_periodo='Octubre-Diciembre' ORDER BY com_n_lin ASC";
    $result_com=mysql_query($query_com) or die ("No se puede ejecutar la consulta: ".$query_com);
	while($row_com=mysql_fetch_array($result_com)){
		$pdf->SetFont('Arial','',7);
		$pdf->SetTextColor(0);
		$pdf->MultiCell(0,4,$row_com['com_n_lin'].'. '.$row_com['com_comentario'],1);
	}
	$pdf->SetFont('Arial','B',8);
	$pdf->SetTextColor(255);
	$pdf->SetFillColor(0);
	$pdf->Cell(0,4,'Conclusiones anuales',0,1,'L',true);
	$pdf->SetFillColor(120);
    $query_com="SELECT * FROM dpo_comentarios WHERE com_dpo_id=".$dpo_id." AND com_periodo='Anuales' ORDER BY com_n_lin ASC";
    $result_com=mysql_query($query_com) or die ("No se puede ejecutar la consulta: ".$query_com);
	while($row_com=mysql_fetch_array($result_com)){
		$pdf->SetFont('Arial','',7);
		$pdf->SetTextColor(0);
		$pdf->MultiCell(0,4,$row_com['com_n_lin'].'. '.$row_com['com_comentario'],1);
	}
$pdf->Output();
?>

